### ISSUE TITLE
Fix improper indent on CCCV1R1p01.html

### ISSUE THREAD

**Issue by robertlugg** [campbellluggblackwell/campbellluggblackwell.com#11]
tidy caused a formatting problem with the top "Volume I" string and date below.  This seemed to be due to a <p> tag inside of a <h1> tag

![image](https://user-images.githubusercontent.com/6054540/116026535-cda42280-a607-11eb-8f1e-6ccb01ee1c49.png)

Proper page:
![image](https://user-images.githubusercontent.com/6054540/116026619-f1676880-a607-11eb-8faf-292a13838ed8.png)

**Comment by robertlugg** [comment]
This was resolved and Bill redid much of the page in the process.

**Comment by ThompsonShapiro** [comment]
Thanks. Since then I've added one more line, a <meta> containing a
description. I'll try doing an edit to insert that one line.

There's something weird about that paragraph of text about Joseph and Ann.
It overflowed the border that was on the original webpage. I forget why
that border was added 20 years ago, but it's not present in the original
hard copy, so I removed it.

On the other hand, the "Campbell Cousins Correspondence" heading wasn't
present in the hard copy of Vol. 1, Rpt. 1 but was there for all the rest
of the CCC Volumes, so I made the editorial decision to add it to give the
web edition of the CCC volumes a more consistent look.

The original hard copy of that page, like the original web version had
wider right and left margins for that paragraph. I tried to style it using
"margin-left:15%; margin-right: 15%;" and several variations of that, but
to no avail. It's more smartphone friendly the way it is, so I let it go. I
ran it through a validator and it got a clean bill of health.
